name: Docker

on:
  push:
    tags:
      - v*
    branches:
      - main
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push PROD Docker image
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v4.0.0
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/leaphy-robotics/leaphy-webbased/leaphy-webbased:prod

      - name: Build and push TEST Docker image
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v4.0.0
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/leaphy-robotics/leaphy-webbased/leaphy-webbased:main

      - name: Clean up old images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'leaphy-webbased'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
